# Generated by Django 4.1.1 on 2022-11-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(default="Let's Write Your First Program!", max_length=200),
        ),
    ]
