# Generated by Django 4.1.1 on 2022-11-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_question_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(default='Explanation'),
        ),
    ]
