# Generated by Django 4.0.4 on 2022-11-08 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_rename_instruction_chapter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importantinstructioncontent',
            old_name='instruction',
            new_name='chapter',
        ),
    ]
